// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// Created by Umi Plugin

export interface IConfigFromPluginsJoi {
huangl250?: {
searchPlaceholder?: string
empty?: string
keyFilter?: string
suggestionKeys?: string[]
groups?: {
groupName?: string
items?: {
key?: string
title?: string
action?: (() => any)
}[]
}[]
}
}
